// Daily motivational quotes for the student dashboard (spec 6.2: a curated list of 100, one per day).
// Proverbs are folk sayings with no single author. Lines marked "INUKA" are our own words of encouragement.
// To add or change a quote, edit this list. Keep each one short and positive.
export const QUOTES = [
  // People
  ['Education is the most powerful weapon which you can use to change the world.', 'Nelson Mandela'],
  ['It always seems impossible until it is done.', 'Nelson Mandela'],
  ['One child, one teacher, one book, one pen can change the world.', 'Malala Yousafzai'],
  ['Knowledge is power. Information is liberating. Education is the premise of progress, in every society, in every family.', 'Kofi Annan'],
  ['A journey of a thousand miles begins with a single step.', 'Lao Tzu'],

  // African proverbs
  ['If you want to go fast, go alone. If you want to go far, go together.', 'African proverb'],
  ['However long the night, the dawn will break.', 'African proverb'],
  ['Little by little, a little becomes a lot.', 'Tanzanian proverb'],
  ['Knowledge is like a garden: if it is not cultivated, it cannot be harvested.', 'Guinean proverb'],
  ['Where you will sit when you are old shows where you stood in youth.', 'Yoruba proverb'],
  ['Smooth seas do not make skilful sailors.', 'African proverb'],
  ['Wisdom is like a baobab tree: no one person can embrace it alone.', 'African proverb'],
  ['When the music changes, so does the dance.', 'African proverb'],
  ['A single bracelet does not jingle.', 'African proverb'],
  ['Rain does not fall on one roof alone.', 'African proverb'],
  ['Do not look where you fell, but where you slipped.', 'African proverb'],
  ['The one who asks questions does not lose the way.', 'African proverb'],
  ['Patience is the mother of a beautiful child.', 'African proverb'],
  ['A river is filled drop by drop.', 'African proverb'],
  ['By crawling, a child learns to stand.', 'African proverb'],
  ['Unity is strength; division is weakness.', 'African proverb'],
  ['No matter how long the rain lasts, there will be a rainbow in the end.', 'African proverb'],
  ['A roaring lion kills no game.', 'African proverb'],
  ['The person who has not travelled widely thinks their mother is the only cook.', 'African proverb'],
  ['You learn how to cut down trees by cutting them down.', 'African proverb'],
  ['When you pray, move your feet.', 'African proverb'],
  ['Sticks in a bundle are unbreakable.', 'African proverb'],
  ['The sun does not forget a village just because it is small.', 'African proverb'],
  ['To get lost is to learn the way.', 'African proverb'],
  ['Seeing is different from being told.', 'African proverb'],
  ['If you are filled with pride, you will have no room for wisdom.', 'African proverb'],
  ['No one tests the depth of a river with both feet.', 'African proverb'],
  ['He who learns, teaches.', 'Ethiopian proverb'],
  ['Hold a true friend with both hands.', 'African proverb'],
  ['A good name shines in the dark.', 'African proverb'],
  ['Many hands make light work.', 'Proverb'],
  ['One who is carried does not know how far the town is.', 'African proverb'],
  ['What you help a child to love can be more important than what you help them to learn.', 'African proverb'],
  ['Do not let what you cannot do stop you from doing what you can.', 'Proverb'],
  ['If you close your eyes to facts, you will learn through accidents.', 'African proverb'],
  ['Tomorrow belongs to the people who prepare for it today.', 'African proverb'],
  ['The best time to plant a tree was 20 years ago. The second best time is now.', 'Proverb'],
  ['A tree is known by its fruit.', 'Proverb'],
  ['Learning expands great souls.', 'Namibian proverb'],
  ['Slowly, slowly, the egg will walk.', 'African proverb'],
  ['A bird builds its nest little by little.', 'African proverb'],
  ['An eye that has seen far is not easily frightened.', 'African proverb'],
  ['Even the tallest tree began as a seed.', 'Proverb'],
  ['Where there is a will, there is a way.', 'Proverb'],
  ['Practice makes perfect.', 'Proverb'],

  // Proverbs from around the world
  ['Do not be afraid of growing slowly; be afraid only of standing still.', 'Chinese proverb'],
  ['Fall seven times, stand up eight.', 'Japanese proverb'],
  ['Learning is a treasure that will follow its owner everywhere.', 'Chinese proverb'],
  ['Teachers open the door, but you must enter by yourself.', 'Chinese proverb'],
  ['The expert in anything was once a beginner.', 'Proverb'],

  // INUKA
  ['Every lesson you finish today is a step towards the university you dream of.', 'INUKA'],
  ['Your story is not over. You are writing the next chapter right now.', 'INUKA'],
  ['Talent is everywhere. Opportunity should be too — and you are going to find yours.', 'INUKA'],
  ['Ten minutes of study today is better than a perfect plan for tomorrow.', 'INUKA'],
  ['Mistakes are proof that you are trying. Keep going.', 'INUKA'],
  ['You do not have to be the best. You only have to be better than you were yesterday.', 'INUKA'],
  ['Where you come from is part of your strength, not a limit on where you can go.', 'INUKA'],
  ['Every great scholar once struggled with the alphabet.', 'INUKA'],
  ['A scholarship application is your story told with courage. Start writing it.', 'INUKA'],
  ['Small daily steps build big futures.', 'INUKA'],
  ['Your phone is a classroom. Use it well today.', 'INUKA'],
  ['Hard days are part of the journey, not the end of it.', 'INUKA'],
  ['Asking for help is a sign of strength. Mentors are here for you.', 'INUKA'],
  ['Read one more page. Learn one more word. That is how fluency grows.', 'INUKA'],
  ['Every expert typist started with two fingers.', 'INUKA'],
  ['Deadlines are not walls. They are reminders to start early.', 'INUKA'],
  ['Believe in the student you are becoming.', 'INUKA'],
  ['The future belongs to those who keep learning.', 'INUKA'],
  ['Your effort today is a gift to your future self.', 'INUKA'],
  ['Rise. Learn. Succeed. One day at a time.', 'INUKA'],
  ['Progress, not perfection.', 'INUKA'],
  ['You are not behind. You are on your own path.', 'INUKA'],
  ['Curiosity is the best teacher. Ask why, and then find out.', 'INUKA'],
  ['Practise speaking English out loud today, even if only to yourself.', 'INUKA'],
  ['A strong application is built one document at a time.', 'INUKA'],
  ['The skills you learn here will stay with you forever.', 'INUKA'],
  ['Your dream university is looking for someone exactly like you.', 'INUKA'],
  ['Showing up every day is a talent too. Keep showing up.', 'INUKA'],
  ['Do something today that your future self will thank you for.', 'INUKA'],
  ['Every "no" brings you closer to your "yes". Keep applying.', 'INUKA'],
  ['You have already overcome so much. You can overcome this lesson too.', 'INUKA'],
  ['Learning a new language opens a new door to the world.', 'INUKA'],
  ['Be proud of how far you have come, and excited about how far you will go.', 'INUKA'],
  ['Your streak is a promise you keep to yourself.', 'INUKA'],
  ['There is no age, place or past that can stop a determined learner.', 'INUKA'],
  ['Write your goals down. Then go after them, one lesson at a time.', 'INUKA'],
  ['Opportunities come to those who are ready. Get ready today.', 'INUKA'],
  ['Courage is starting even when you are not sure you will finish.', 'INUKA'],
  ['The world needs your ideas. Education will help you share them.', 'INUKA'],
  ['Every certificate you earn is proof of your hard work.', 'INUKA'],
  ['Stay curious, stay humble, stay hungry to learn.', 'INUKA'],
  ['Today is a good day to learn something new.', 'INUKA'],
  ['You belong in every classroom you dream of entering.', 'INUKA'],
  ['Learning together makes everyone stronger. Help a friend today.', 'INUKA'],
  ['Every page you read today is an investment in your future.', 'INUKA'],
];

export const quoteOfTheDay = (date = new Date()) => {
  const day = Math.floor((date.getTime() - date.getTimezoneOffset() * 60000) / 864e5); // changes at local midnight
  const [text, author] = QUOTES[day % QUOTES.length];
  return { text, author };
};
